version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stabl
jobs:
  my-job-name:e

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          df -BG

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
