version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/s4030/Circh/environment-variables
          username: root 
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          df -BG

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
